### ISSUE TITLE
Cannot add value of type 'VlcControl'

### ISSUE THREAD

**Issue by Dokman** [ZeBobo5/Vlc.DotNet#275]
So what i can do, it do this error with vs 2015 and vs 2017 how i can fix it?

**Comment by jeremyVignelles** [comment]
Without any piece of code, that would be very hard to help.
This issue tracker is meant to track issues that should be fixed in Vlc.DotNet, not about generic coding errors. For that kind of message, I would rather post it with an example code on StackOverflow ;)

**Comment by Reyth3** [comment]
Here it is:

    <Window x:Class="VLC_Subplayer.MainWindow"
            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
            xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
            xmlns:vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf"
            xmlns:local="clr-namespace:VLC_Subplayer"
            mc:Ignorable="d"
            Title="VLC Subplayer" Height="600" Width="800">
        <DockPanel>
            <Menu DockPanel.Dock="Top">
                <MenuItem Header="File">
                    <MenuItem Header="Open... " Click="OpenFile" />
                </MenuItem>
            </Menu>
            <Grid>
                <vlc:VlcControl Name="vlc" />
            </Grid>
        </DockPanel>
    </Window>

The control doesn't seem to be detected by the XAML parser, so it throws two errors:

    Severity	Code	Description	Project	File	Line	Suppression State
    Error		A value of type 'VlcControl' cannot be added to a collection or dictionary of type 
    'UIElementCollection'.	VLC Subplayer	...\Documents\Visual Studio 2017\Projects\VLC 
    Subplayer\VLC Subplayer\MainWindow.xaml	17	
    Error		The property 'Name' was not found in type 'VlcControl'.	VLC Subplayer	
    ...Documents\Visual Studio 2017\Projects\VLC Subplayer\VLC Subplayer\MainWindow.xaml	17	

After the build finishes, it actually starts working in the code-behind file. Until you try to run it, that is.

Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll

Additional information: Cannot create instance of 'MainWindow' defined in assembly 'VLC Subplayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Exception has been thrown by the target of an invocation.  Error in markup file 'MainWindow.xaml' Line 1 Position 9.

Removing the `VlcControl` from XAML fixes the issue, but that kind of fix is not exactly an acceptable fix.

Also tried:

* Switching target to .NET Framework 4.0, 4.5, 4.5.1, 4.6
* Installing a previous version of the package from NuGet;
* Building for both x86 and x64;
* Building `Vlc.DotNet` from source and referencing the dlls;

No code for the control itself seems to be called, most likely because the `VlcControl` itself doesn't get initialized:

    public MainWindow()
    {
        InitializeComponent();
        vlc.MediaPlayer.EndInit(); // Nope
        vlc.MediaPlayer.Log += MediaPlayer_Log; // Nope
        vlc.MediaPlayer.VlcLibDirectoryNeeded += MediaPlayer_VlcLibDirectoryNeeded; // Nope
    }

Same thing happens with the samples from this repo.

Hope that's enough code and detail.

**Comment by jeremyVignelles** [comment]
Thanks for the code.
My first guess is that this error is causing the issue:
```
The property 'Name' was not found in type 'VlcControl'
```

Indeed, you are using the "Name" property, which does not exist on VlcControl. It exist on other elements (like `<Window>`, or `<Grid>`) because they are "built-in" and the xmlns namespace of the `Name` is known. If you are using a component with a custom namespace, for your case `<vlc:`, you are outside that scope and `Name` is not known, you need to prefix it:

`<vlc:VlcControl x:Name="vlc" />`

Please tell me if that fixes the issue

**Comment by Reyth3** [comment]
Yes, as a matter of fact, that did help somewhat. Thanks a bunch! I really shoul've been able to figure this out but hey, it works either way.

Referencing the `x` namespace did solve that one error, I also got rid of the `XamlParserException` by moving the `.EndInit()` call below the event declarations, but `VlcControl` itself is still throwing the same error:

    A value of type 'VlcControl' cannot be added to a collection or dictionary of type 
'UIElementCollection'.

Then again, it doesn't seem to be that much of an issue anymore.

Thanks!

**Comment by jeremyVignelles** [comment]
Glad it helped. regarding the issue, it reminds me of the time I was missing a weird reference in the project (something like Automation provider or something?) and visual studio designer was yelling at me like that. after comparing references with a fresh wpf project, I was able to add the missing bits and the warnings stopped (after restarting vs, maybe?)
