### ISSUE TITLE
How to rotate the video ?

### ISSUE THREAD

**Issue by AioRos85** [ZeBobo5/Vlc.DotNet#86]
Whether there is a property can be set ?

**Comment by Beast76** [comment]
Hi,

my try to set the parameters on SetMedia won`t work.

       vlcControl.MediaPlayer.SetMedia(new Uri("http://......"), "--video-filter=transform", "--transform-type=90");

Solution:
I have this problem solved by overload the VlcMediaPlayer internal constructor with additional options.

        internal VlcMediaPlayer(VlcManager manager, string[] options)
        {
            Manager = manager;
            Manager.CreateNewInstance(options);

            myMediaPlayerInstance = manager.CreateMediaPlayer();
            RegisterEvents();
            Chapters = new ChapterManagement(manager, myMediaPlayerInstance);
            SubTitles = new SubTitlesManagement(manager, myMediaPlayerInstance);
            Video = new VideoManagement(manager, myMediaPlayerInstance);
            Audio = new AudioManagement(manager, myMediaPlayerInstance);
        }

After this I added on VlcControl this options to set this from external

        public string[] VlcMediaPlayerOptions { get; set; }

and on EndInit() of VlcControl I handled this options

        public void EndInit()
        {
            if (IsInDesignMode() || myVlcMediaPlayer != null)
                return;
            if (VlcLibDirectory == null && (VlcLibDirectory = OnVlcLibDirectoryNeeded()) == null)
            {
                throw new Exception("'VlcLibDirectory' must be set.");
            }

            if (VlcMediaplayerOptions == null)
            {
                myVlcMediaPlayer = new VlcMediaPlayer(VlcLibDirectory);
            }
            else
            {
                myVlcMediaPlayer = new VlcMediaPlayer(VlcLibDirectory, VlcMediaPlayerOptions);
            }
            myVlcMediaPlayer.VideoHostControlHandle = Handle;
            RegisterEvents();
        }

usage: Now you can use the command line options.

       vlcControl.MediaPlayer.VlcMediaPlayerOptions = new[] { "--quiet",
                                                              "--video-filter=transform",
                                                              "--transform-type=90" 
                                                            };

This is certainly not the most elegant way, but it did at least for now solved my problem.

**Comment by rusoaica** [comment]
I have tried using your example, but unfortunately, it has no effect for me. I set the options before setting the media and calling Play(), the video starts playing, but the options are completely ignored, even though while debugging i can see that they are set. I even have tried with different options, like "--video-filter=magnify", and still no change in the video. What am I doing wrong, or is there any other way of setting options? 
Thank you!

**Comment by aaqib7git** [comment]
Hi,
I'm unable to rotate the video using:
`vlcControl.MediaPlayer.VlcMediaPlayerOptions = new[] { "--quiet",
                                                          "--video-filter=transform",
                                                          "--transform-type=90" 
                                                        };`

I am using the latest build from the master branch. libVlc version is: 2.1

The options seem to be ignored and nothing happens when arguments/options are passed.
Thanks

**Comment by ricardoschiller** [comment]
Have you ( @rusoaica , @aaqib7git ) solved this problem already? The code by @Beast76 is already on the latest version, but it doesn't work. I really need to make this work...Help please!

**Comment by jeremyVignelles** [comment]
Is this still an issue? `VlcMediaPlayerOptions` is now available (It must be initialized before EndInit()) and should do the trick. Please reopen if the issue is still present.
